# -*- mode: ruby -*-
# vi: set ft=ruby :

HOSTNAME_MACHINE = "kernel_mod.box"

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure(2) do |config|
	hostname = HOSTNAME_MACHINE
	locale = "en_GB.UTF.8"
	# Box
	config.vm.box = "ubuntu/bionic64"
	# Shared folders
    config.vm.synced_folder "../src", "/src", owner: "vagrant", group: "vagrant"
    

	# Removes "stdin: is not a tty" annoyance as per
	# https://github.com/SocialGeeks/vagrant-openstack/commit/d3ea0695e64ea2e905a67c1b7e12d794a1a29b97
	config.ssh.shell = "bash -c 'BASH_ENV=/etc/profile exec bash'"

	#setup X-Forwarding
	config.ssh.forward_x11 = true


	config.vm.provider "virtualbox" do |vb|
		vb.customize	[
			"modifyvm", :id,
			'--cableconnected1', 'on',
			"--memory", 1024,
			]

		# Allow the creation of symlinks for nvm
		# http://blog.liip.ch/archive/2012/07/25/vagrant-and-node-js-quick-tip.html
		vb.customize ["setextradata", :id, "VBoxInternal2/SharedFoldersEnableSymlinksCreate/vagrant","1"]
	end
end
